options:
    code_archive:
        default: ''
        type: string 
        description: >
            The location of the code archive to install. This can be either:
            - a relative path within the charm (e.g. "files/my-project.v1.bzip2")
            - a URL (e.g. "https://example.com/my-project.v1.tar.gz")
            Changing this settings will update the app.
    wsgi_application:
        default: ''
        type: string
        description: >
            The WSGI application within the archive, in Python notation
            E.g.: my_app.wsgi:application
    requirements_path:
        default: ''
        type: string
        description: >
            The location of the requirements file within the archive.
            Requirements in this file will be installed with `pip install`
    pip_cache_path:
        default: ''
        type: string
        description: >
            The location of the pip-cache to install requirements from.
            If pip-cache is present, pip will not attempt to connect to PyPi,
            and instead look for requirements in the specified cache folder.
    apt_dependencies:
        default: ''
        type: string
        description: A space-separated list of apt dependencies to install
    nagios_index_content:
        default: ""
        type: string
