options:
    build_label:
        default: ""
        type: string
        description: >
            The build label given to the code archive and corresponding to
            the path from which the archived code should be installed.
            For example, a value of 'r2' tells the charm to use
            the archive at 'r2/code_archive.tgz'.
    archive_filename:
        default: ""
        type: string
        description: >
            The filename for the archive - e.g. "code_archive.tgz"
    current_symlink:
        default: "latest"
        type: string
        description: |
            The symlink of the code to run. The default of 'latest' will use
            the most recently added build on the instance.  Specifying a
            differnt label (eg. "r235") will symlink to that directory assuming
            it has been previously added to the instance.
    requirements_path:
        default: ''
        type: string
        description: >
            The location of the requirements file within the archive.
            Requirements in this file will be installed with `pip install`
    pip_cache_path:
        default: ''
        type: string
        description: >
            The location of the pip-cache to install requirements from.
            If pip-cache is present, pip will not attempt to connect to PyPi,
            and instead look for requirements in the specified cache folder.
    apt_dependencies:
        default: ''
        type: string
        description: A space-separated list of apt dependencies to install
    nagios_index_content:
        default: ""
        type: string
