options:
    build_label:
        default: ""
        type: string
        description: >
            The build label given to the code archive and corresponding to
            the path from which the archived code should be installed.
            For example, a value of 'r2' tells the charm to use
            the archive at 'r2/example-wsgi-app.tar.bzip2'.
