---
- hosts: localhost

  vars:
    - app_label: wsgi-app.example.com

  roles:
    - role: wsgi-app
      listen_port: 8080
      wsgi_application: example_wsgi:application
      code_archive: "{{ build_label }}/example-wsgi-app.tar.bzip2"
      when: build_label != ''

    - role: nrpe-external-master
      check_name: check_http
      check_params: "-I 127.0.0.1 -p 8080 -e ' 200 OK' -s 'It works!' -u '/'"
      service_description: "Verify wsgi-example is responding."

  tasks:
    # Apt dependencies
    # ===
    - name: Install custom apt dependencies.
      apt: "pkg={{ item }} state=latest update_cache=yes"
      with_items: apt_dependencies.split()
      tags:
        - config-changed

    # Pip requirements
    # ===
    - name: Install pip if we need to install requirements.
      apt: "pkg={{ item }} state=latest update_cache=yes"
      with_items:
        - python-pip
      tags:
        - config-changed
      when: requirements_path > ""

    - name: Install pip requirements from PyPi
      pip: "requirements='{{ current_code_dir }}/{{ requirements_path }}'"
      tags:
        - config-changed
      when: requirements_path > "" and pip_cache_path == ""

    - name: Install pip requirements from pip cache
      pip: "requirements='{{ current_code_dir }}/{{ requirements_path }}' extra_args='--no-index --find-links={{ current_code_dir }}/{{ pip_cache_path }}'"
      tags:
        - config-changed
      when: requirements_path > "" and pip_cache_path > ""
