---
- hosts: localhost

  roles:
    - role: wsgi-app
      listen_port: 8080

    - role: nrpe-external-master
      check_name: check_http
      check_params: "-I 127.0.0.1 -p 8080 -e ' 200 OK' -s '{{ nagios_index_content }}' -u '/'"
      service_description: "Verify wsgi-example is responding."
      when: nagios_index_content > ''

  tasks:
    # Apt dependencies
    # ===
    - name: Install custom apt dependencies.
      apt: "pkg={{ item }} state=latest update_cache=yes"
      with_items: apt_dependencies.split()
      tags:
        - config-changed
