---
- hosts: localhost

  vars:
    - app_label: wsgi-app.example.com

  roles:
    - role: wsgi-app
      listen_port: 8080
      wsgi_application: example_wsgi:application
      code_archive: "{{ build_label }}/example-wsgi-app.tar.bzip2"
      when: build_label != ''

    - role: nrpe-external-master
      check_name: check_http
      check_params: "-I 127.0.0.1 -p 8080 -e ' 200 OK' -s 'It works!' -u '/'"
      service_description: "Verify wsgi-example is responding."

  tasks:
    # Apt dependencies
    # ===
    - name: Install custom apt dependencies.
      apt: "pkg={{ item }} state=latest update_cache=yes"
      with_items: apt_dependencies.split()
      tags:
        - config-changed
