---
- include: setup-machine.yml
- include: setup-code.yml

- name: Symlink current version of application code
  tags:
    - config-changed
  file:
    src: "{{ current_code_dir }}"
    dest: "{{ code_dir }}/current"
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
    state: link

- name: Set wsgi details if relation defined
  tags:
    - wsgi-file-relation-changed
    - config-changed
  command: >
    relation-set -r {{ item.key }}
    project_name={{ app_label }}
    working_dir={{ code_dir }}/current
    python_path={{ python_path }}
    wsgi_user={{ wsgi_user }}
    wsgi_group={{ wsgi_group }}
    port={{ listen_port }}
    wsgi_access_logfile={{ log_dir }}/{{ app_label }}-access.log
    wsgi_wsgi_file={{ wsgi_application }}
    wsgi_extra=--error-logfile={{ log_dir }}/{{ app_label }}-error.log
    env_extra='{{ env_extra }}'
    timestamp={{ ansible_date_time.iso8601_micro }}
  when: relations['wsgi-file']
  with_dict: relations['wsgi-file']

- name: Set the website relation if defined.
  tags:
    - website-relation-changed
    - config-changed
  command: >
    relation-set -r {{ item.key }}
    hostname={{ ansible_default_ipv4.address }}
    port={{ listen_port }}
  when: relations['website']
  with_dict: relations['website']

- name: Manually set current symlink.
  tags:
    - set-current-symlink
  file:
    src: "{{ code_dir }}/{{ ansible_env.CURRENT_SYMLINK }}"
    dest: "{{ code_dir }}/current"
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
    state: link
  notify:
    - Restart wsgi
