---
- name: "If code_archive is a path, copy from the path"
  tags:
    - config-changed
  copy:
    src: "{{ charm_dir }}/{{ code_archive }}"
    dest: "{{ archives_dir }}"
    force: no
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
    mode: 0644
  when: "code_archive > '' and 'http://' not in code_archive and 'https://' not in code_archive"

- name: "If code_archive is a URL, download code archive"
  tags:
    - config-changed
  get_url:
    url: "{{ code_archive }}"
    dest: "{{ archives_dir }}"
    force: no
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
    mode: 0644
  when: "'http://' in code_archive or 'https://' in code_archive"

- name: Check if archive is already extracted
  tags:
    - config-changed
  stat: path={{ current_code_dir }}/EXTRACTED
  register: already_extracted

- name: Extract built app sourcecode.
  tags:
    - config-changed
  unarchive:
    src: "{{ archive_path }}"
    dest: "{{ current_code_dir }}"
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
  when: code_archive > "" and already_extracted.stat.exists == False

# The following is only necessary because the unarchived code files
# won't have the correct user/group.
- name: Set user/group for application directory.
  tags:
    - config-changed
  file: path={{ code_dir }} state=directory owner={{ wsgi_user }} group={{ wsgi_group }} recurse=yes
  when: already_extracted.stat.exists == False

- name: Touch a file to ensure that we don't extract the same archive again.
  command: /usr/bin/touch {{ current_code_dir }}/EXTRACTED
  tags:
    - config-changed
  when: already_extracted.stat.exists == False
